name: LaTeX CI

on:
  push:
    branches: [ master ]
    paths:
    - '**.tex'
  pull_request:
    branches: [ master ]
    paths:
    - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.5
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: cv.tex
        args: -lualatex --file-line-error --interaction=nonstopmode
    - name: Upload LaTeX build
      uses: actions/upload-artifact@v2-preview
      with:
        path: cv.pdf
