name: LaTeX CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - '**.tex'
  pull_request:
    branches: [ master ]
    paths:
    - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: cv.tex
        args: -lualatex --file-line-error --interaction=nonstopmode
    - name: Upload LaTeX build
      uses: actions/upload-artifact@v3.1.2
      if: always()
      with:
        path: cv.*
