name: "🤖 New tag -> release"

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
      - name: "Compile LaTeX document"
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
          args: -lualatex --file-line-error --interaction=nonstopmode
      - id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: "Upload .aar"
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cv.pdf
          asset_name: cv-${{ steps.vars.outputs.tag }}.pdf
          asset_content_type: application/zip
