name: "Create a tag"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: "New tag"
        run: |
          git tag v${{ github.event.inputs.tag }}
          git push --tags
